apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-php-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache-php
  template:
    metadata:
      labels:
        app: apache-php
    spec:
      containers:
      - name: apache-php
        image: sventur/apache_php
        ports:
        - containerPort: 80
        volumeMounts:
        - name: apache-storage
          mountPath: "/var/www/html" # Monta NFS qui
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName  # Imposta NODE_NAME con il nome del nodo corrente
      volumes:
      - name: apache-storage
        persistentVolumeClaim:
          claimName: nfs-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: apache-php-service
  labels:
    app: apache-php
spec:
  type: LoadBalancer  # Cambiato da NodePort a LoadBalancer
  selector:
    app: apache-php
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
